name: earth-analytics-python
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pip
  # Core scientific python
  - numpy
  - pyqt
  - tqdm
  - kiwisolver
  
  # Plotting
  - matplotlib
  - plotly
  - seaborn

 
  # Natural language processing
  - nltk
  - textblob

 
