name: earth-analytics-python
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pip
  # Core scientific python
  - numpy
 
  # Plotting
  - matplotlib
  - plotly 
  # Natural language processing
  - nltk
  - textblob

 
